let IDX=null;const CACHE=new Map();const $=s=>document.querySelector(s);
const GROUP_GAP_SECONDS=30,DISPLAY_PADDING_SEGMENTS=1;
function norm(s=""){return s.normalize("NFKC").replace(/[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]/g,"").replace(/[أإآٱ]/g,"ا").replace(/ى/g,"ي").replace(/ؤ/g,"و").replace(/ئ/g,"ي").replace(/ة/g,"ه").replace(/ـ/g,"").toLowerCase().replace(/\s+/g," ").trim()}
function esc(s=""){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]||c))}
// Correct > mapping separately to keep source readable.
function escapeHtml(s=""){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function parse(q){q=norm(q);if(!q)return null;return q.split(/\s+or\s+/i).map(g=>g.split(/\s+and\s+/i).map(x=>x.trim().replace(/^["']|["']$/g,"")).filter(Boolean)).filter(g=>g.length)}
function match(t,g){return g&&g.some(a=>a.every(term=>t.includes(term)))}
function time(s){s=Math.max(0,Math.floor(s||0));let h=Math.floor(s/3600),m=Math.floor((s%3600)/60),z=s%60;return h?`${h}:${String(m).padStart(2,"0")}:${String(z).padStart(2,"0")}`:`${m}:${String(z).padStart(2,"0")}`}
function at(url,s){return `${url}${url.includes("?")?"&":"?"}t=${Math.floor(s)}s`}
function arabic(s){return /[\u0600-\u06FF]/.test(s||"")}
function queryWords(groups){if(!groups)return[];const words=[];for(const ag of groups)for(const term of ag)for(const w of term.split(/\s+/)){const n=norm(w);if(n&&!words.includes(n))words.push(n)}return words}
function highlightText(text,groups){const wanted=queryWords(groups);if(!wanted.length)return escapeHtml(text);return(text||"").split(/(\s+)/).map(part=>{if(/^\s+$/.test(part))return part;const core=part.replace(/^[^\p{L}\p{N}]+|[^\p{L}\p{N}]+$/gu,"");const n=norm(core);const hit=wanted.some(w=>n===w||(w.length>=3&&n.includes(w)));return hit?`<mark>${escapeHtml(part)}</mark>`:escapeHtml(part)}).join("")}
function findHitIndexes(v,groups){const hits=[];for(let i=0;i<v.segments.length;i++){const t=norm([v.segments[i-1]?.search||"",v.segments[i]?.search||"",v.segments[i+1]?.search||""].join(" "));if(match(t,groups))hits.push(i)}return hits}
function groupHitIndexes(v,h){if(!h.length)return[];const gs=[];let c=[h[0]];for(let n=1;n<h.length;n++){const p=c[c.length-1],q=h[n];if((v.segments[q].start||0)-(v.segments[p].start||0)<=GROUP_GAP_SECONDS)c.push(q);else{gs.push(c);c=[q]}}gs.push(c);return gs}
function passageForGroup(v,g){const f=g[0],l=g[g.length-1],a=Math.max(0,f-DISPLAY_PADDING_SEGMENTS),b=Math.min(v.segments.length-1,l+DISPLAY_PADDING_SEGMENTS);return{start:v.segments[f].start||0,end:(v.segments[l].start||0)+(v.segments[l].duration||0),text:v.segments.slice(a,b+1).map(x=>x.text).join(" ")}}
async function loadScholar(id){if(CACHE.has(id))return CACHE.get(id);const s=IDX.scholars.find(x=>x.id===id);if(!s)return[];const chunks=await Promise.all((s.files||[]).map(async f=>{const r=await fetch(`ytarchive-data/${f}`,{cache:"no-store"});if(!r.ok)throw Error(`${f}: ${r.status}`);return(await r.json()).videos||[]}));const vids=chunks.flat();CACHE.set(id,vids);return vids}
async function selectedVideos(){const id=$("#channel").value;if(id)return loadScholar(id);const all=await Promise.all(IDX.scholars.map(s=>loadScholar(s.id)));return all.flat()}
async function search(){const q=$("#query").value.trim(),groups=parse(q);if(!q){$("#status").textContent=`${IDX.searchable_count.toLocaleString()} searchable videos · enter a search above`;$("#results").innerHTML="";return}$("#status").textContent="Loading scholar archive…";try{const videos=await selectedVideos();const passages=[],seen=new Set();for(const v of videos){if(v.transcript_status!=="available")continue;const hits=findHitIndexes(v,groups);if(!hits.length)continue;for(const g of groupHitIndexes(v,hits)){passages.push({v,...passageForGroup(v,g)});seen.add(v.id);if(passages.length>=300)break}if(passages.length>=300)break}$("#status").textContent=`${passages.length.toLocaleString()} matching passage${passages.length===1?"":"s"} in ${seen.size.toLocaleString()} video${seen.size===1?"":"s"}`+(passages.length>=300?" · first 300 shown":"");if(!passages.length){$("#results").innerHTML='<div class="empty">No matching passages found.</div>';return}$("#results").innerHTML=passages.map(p=>{const v=p.v,dir=arabic(p.text)?"rtl":"ltr",td=arabic(v.title)?"rtl":"ltr",d=v.upload_date&&v.upload_date.length===8?`${v.upload_date.slice(0,4)}-${v.upload_date.slice(4,6)}-${v.upload_date.slice(6,8)}`:"",range=(Math.floor(p.end)>Math.floor(p.start)+2)?`<span class="passage-range">passage ${time(p.start)}–${time(p.end)}</span>`:"";return `<article class="result"><h2 dir="${td}">${escapeHtml(v.title)}</h2><div class="meta">${escapeHtml(v.scholar_name||v.channel)} · source: ${escapeHtml(v.channel||"")} · ${time(p.start)} ${range}${d?` · ${d}`:""}${v.caption_language?` · ${escapeHtml(v.caption_language)}`:""}${v.caption_kind?` ${escapeHtml(v.caption_kind)}`:""}</div><p class="transcript" dir="${dir}">${highlightText(p.text,groups)}</p><a class="watch" href="${at(v.url,p.start)}" target="_blank" rel="noopener">Watch on YouTube at ${time(p.start)} →</a></article>`}).join("")}catch(e){$("#status").textContent="Could not load archive data.";console.error(e)}}
async function init(){try{const r=await fetch("ytarchive-index.json",{cache:"no-store"});if(!r.ok)throw Error(r.status);IDX=await r.json();for(const s of IDX.scholars||[]){const o=document.createElement("option");o.value=s.id;o.textContent=`${s.name} (${s.searchable_count})`;$("#channel").appendChild(o)}$("#status").textContent=`${IDX.searchable_count.toLocaleString()} searchable videos across ${IDX.scholars.length.toLocaleString()} scholar${IDX.scholars.length===1?"":"s"}`}catch(e){$("#status").textContent="Could not load ytarchive-index.json.";console.error(e)}}
$("#go").onclick=search;$("#query").addEventListener("keydown",e=>{if(e.key==="Enter")search()});$("#channel").onchange=()=>{if($("#query").value.trim())search()};init();
